networks:
  ragnarok-net:
    name: ragnarok-net


services:
  hercule-db:
    image: mysql:8.0-bookworm
    volumes:
      - ./:/home/hercuser/Hercules
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./check_script_end.sh:/check_script_end.sh
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVER_RENEWAL_MODE: PRERENEWAL
      CHECK_FILE: /var/lib/mysql/database_ready
    healthcheck:
          test: ["CMD", "/check_script_end.sh"]
          interval: 15s
          timeout: 5s
          retries: 50 
          start_period: 30s
    networks:
      ragnarok-net:
    labels:
      - ragnarok-webserv-dashboard.show=true

# export UID=$(id -u)
# export GID=$(id -g)
# docker-compose up
  
  builder:
    build: ./docker-builder
    volumes:
      - ./:/home/hercuser/Hercules
      - ./docker_start.sh/:/docker_start.sh
    environment:
      COMPILE_SERVER: false 
      PACKETVER: 20200401
      # PACKETVER: 20250716
      ENABLE_RENEWAL_PACKET: "no" # yes or no
    command: ["/docker_start.sh"]

  login-server:
    build: ./docker-builder
    volumes:
      - ./:/home/hercuser/Hercules
      - ./docker_start.sh/:/docker_start.sh
    environment:
      COMPILE_SERVER: false
      SERVER_TYPE: login-server
    depends_on:
      hercule-db:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - 6900:6900
    command: ["/docker_start.sh"]
    networks:
      ragnarok-net:
    labels:
      - ragnarok-webserv-dashboard.show=true


  char-server:
    build: ./docker-builder
    volumes:
      - ./:/home/hercuser/Hercules
      - ./docker_start.sh/:/docker_start.sh
    environment:
      COMPILE_SERVER: false
      SERVER_TYPE: char-server
    depends_on:
      hercule-db:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - 6121:6121
    command: ["/docker_start.sh"]
    networks:
      ragnarok-net:
    labels:
      - ragnarok-webserv-dashboard.show=true

  map-server:
    build: ./docker-builder
    volumes:
      - ./:/home/hercuser/Hercules
      - ./docker_start.sh/:/docker_start.sh
    environment:
      COMPILE_SERVER: false
      SERVER_TYPE: map-server
    depends_on:
      hercule-db:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - 5121:5121
    command: ["/docker_start.sh"]
    networks:
      ragnarok-net:
    labels:
      - ragnarok-webserv-dashboard.show=true

  api-server:
    build: ./docker-builder
    volumes:
      - ./:/home/hercuser/Hercules
      - ./docker_start.sh/:/docker_start.sh
    environment:
      COMPILE_SERVER: false
      SERVER_TYPE: api-server
    depends_on:
      hercule-db:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - 7121:7121
    command: ["/docker_start.sh"]
    networks:
      ragnarok-net:
    labels:
      - ragnarok-webserv-dashboard.show=true

